plugins {
	id 'fabric-loom' version '1.7.4'
	id 'maven-publish'
	id "com.modrinth.minotaur" version "2.+"
	id 'com.matthewprenger.cursegradle' version '1.+'
}

def sodium_versions = sodium_version.split("-")
def isSodiumBeta = sodium_versions.length > 2 && sodium_versions[2].contains("beta")

def upload_ready_mod_version = "mc\( {minecraft_version}- \){project.mod_version}-sodium${sodium_versions[1]}"
if (isSodiumBeta) upload_ready_mod_version += sodium_versions[2]

def supp_mc_versions = new ArrayList<String>()
supp_mc_versions.add(minecraft_version)

def scss_release_type = "release"

if (!additional_supported_mc_versions.isEmpty()) {
	def versions = additional_supported_mc_versions.split(",")
	for (final def v in versions) {
		supp_mc_versions.add(v)
	}
}

version = upload_ready_mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
		content {
			includeGroup "maven.modrinth"
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	modImplementation "maven.modrinth:sodium:${project.sodium_version}"
}

if (project.hasProperty("modrinthToken")) {
	modrinth {
		token = modrinthToken
		projectId = 'G8yJPRdl'
		versionNumber = upload_ready_mod_version
		versionName = 'SodiumCoreShaderSupport'
		uploadFile = remapJar
		gameVersions = supp_mc_versions
		loaders = ['fabric']
		versionType = scss_release_type
		changelog = mod_changelog
	}
}

if (project.hasProperty("curseForgeToken")) {
	curseforge {
		apiKey = curseForgeToken
		project {
			id = '956376'
			releaseType = scss_release_type
			changelog = mod_changelog
			for (final def v in supp_mc_versions)
				addGameVersion v

			mainArtifact(remapJar) {
				displayName = "Sodium Core Shader Support $minecraft_version $upload_ready_mod_version"
			}
		}
	}
}

processResources {
	def svp = sodium_versions[1] + "+" + sodium_versions[0]

	if (isSodiumBeta)
		svp = sodium_versions[1] + "-" + sodium_versions[2] + "+" + sodium_versions[0]

	String mcVerArray = "[ \"" + supp_mc_versions[0] + "\""
	for (int i = 1; i < supp_mc_versions.size(); i++)
		mcVerArray += ", \"" + supp_mc_versions.get(i) + "\""

	mcVerArray += "]"

	inputs.property "version", project.version
	inputs.property "sodium_version", svp
	inputs.property "loader_version", loader_version
	inputs.property "minecraft_version", mcVerArray

	filesMatching("fabric.mod.json") {
		expand "version": project.version,
				"sodium_version": svp,
				"loader_version": loader_version,
				"minecraft_version": mcVerArray
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	from("LICENSE") {
		rename { "\( {it}_ \){project.base.archivesName.get()}" }
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
